---
title: "Wrangling"
format:
  html:
    theme: default
---

## Libraries

```{r}
library(tidyverse)
library(here)
library(recipes)#Creating unordered factors/ordered factors
```

## Load Data

```{r}
d<- readRDS(here("fluanalysis", "data", "SympAct_Any_Pos.Rda"))
```

## Remove Columns of non-interest

```{r}
d1<- d %>%
  select(-contains(c("FluA", "FluB", "Score", "Total", "Dxname", "Activity", "Unique.Visit"))) %>% #Removes Columns of non-interest 
drop_na() #Drop NAs
```

**Now we have a data set with no NAs and presence/absence of flu symptoms (categorical), and body temperature (continuous)**

## Remove Variables with multiple levels/ Yes-No

```{r}
d2<- 
  d1 %>%
  select(!c(WeaknessYN, CoughYN, MyalgiaYN, CoughYN2))
```

## Recode as ordered/unordered

```{r}
cat <- #Create Dataframe with just categorical variables
  d2 %>% 
  select(!c(Weakness, CoughIntensity, Myalgia, BodyTemp)) %>%
  step_dummy(all_predictors())#???

ord<- #Create df with just ordinal variables
  d2 %>%
  select(Weakness, CoughIntensity, Myalgia) %>%
  step_ordinalscore(all_predictors())#????
    

```

## Remove Binary predictors that have\<50 entries in one category

```{r}
rec<- 
  d2 %>%
  step_nzv(all_predictors())
```

Save RDS

```{r}
saveRDS(d2, file= here("fluanalysis", "data", "SypAct_clean.rds"))
```
